export const ErrorCodes = {
  // Auth errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // File operation errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  FILE_OPERATION_FAILED: 'FILE_OPERATION_FAILED',
  PATH_TRAVERSAL_ATTEMPT: 'PATH_TRAVERSAL_ATTEMPT',

  // Connection errors
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  HOST_UNREACHABLE: 'HOST_UNREACHABLE',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',

  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DUPLICATE_ERROR: 'DUPLICATE_ERROR',
  
  // Permission errors
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  
  // Other errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
